development:
  title  : Joruri Mail
  uri    : http://192.168.0.2/
  proxy  :
  map_key:
  mail_domain: localhost.localdomain.jp

test:
  title  : Joruri Mail
  uri    : http://192.168.0.2/
  proxy  :
  map_key:
  mail_domain: localhost.localdomain.jp

production:
  title  : Joruri Mail
  uri    : http://192.168.0.2/
  proxy  :
  map_key:
  mail_domain: localhost.localdomain.jp
