development:
  host: 192.168.0.3
  port: 389
  base: dc=www,dc=joruri,dc=org

test:
  host: 192.168.0.3
  port: 389
  base: dc=www,dc=joruri,dc=org

production:
  host: 192.168.0.3
  port: 389
  base: dc=www,dc=joruri,dc=org
