development:
  address: localhost
  port: 25
  domain: localhost.localdomain.jp
  user_name:
  password:
  authentication:

test:
  address: localhost
  port: 25
  domain: localhost.localdomain.jp
  user_name:
  password:
  authentication:

production:
  address: localhost
  port: 25
  domain: localhost.localdomain.jp
  user_name:
  password:
  authentication:
