- id: enabled
  name: 有効
- id: disabled
  name: 無効
- id: visible
  name: 表示
- id: hidden
  name: 非表示
- id: draft
  name: 下書き
- id: recognize
  name: 承認待ち
- id: recognized
  name: 公開待ち
- id: prepared
  name: 公開
- id: public
  name: 公開中
- id: closed
  name: 非公開
- id: completed
  name: 完了
