development:
  adapter :
  database:
  username:
  password:
  timeout :
  encoding:
  host:

test:
  adapter :
  database:
  username:
  password:
  timeout :
  encoding:
  host:

production:
  adapter : mysql
  database: jorurimail
  username: joruri
  password: pass
  timeout : 5000
  encoding: utf8
  host: 127.0.0.1

