development:
  host: 192.168.52.137
  port: 389
  base: dc=city,dc=zomeki,dc=jp
  # Active Directory
  #host: 192.168.32.78
  #port: 389
  #base: dc=pref,dc=tokushima,dc=jp
  #domain: pref.tokushima.jp
  #bind_dn: "[uid]@[domain]"
  #charset: Shift_JIS

test:
  host: 192.168.0.3
  port: 389
  base: dc=www,dc=joruri,dc=org

production:
  host: 192.168.0.3
  port: 389
  base: dc=www,dc=joruri,dc=org
